# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Jose Luis Bergonio's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Jose Luis Bergonio
headline: Registered Mechanical Engineer - Cum Laude
description: >- # dont remove this line. this will ignore all new lines until the next section
<div style="text-align: justify"> Fresh graduate in Mechanical Engineering from Mapúa Malayan Colleges Laguna and a recent passer of the February 2025 Mechanical Engineering Licensure Examination.** 
Experienced in mechanical design, thermodynamics, and system analysis, with hands-on involvement in academic projects and internship training. His undergraduate research focused on developing a **solar air dryer with perforated baffles and 
thermal storage** for drying coconut briquettes, reflecting his interest in **renewable energy and sustainability**. During college, he served as **Marketing Director** of the student-governing body of the Mapúa Institute of Technology at Laguna, 
where he gained experience in leadership, campaign strategy, and student engagement. Beyond engineering, he is skilled in **photo/video editing, coding, and technical communication**. Highly motivated, detail-oriented, and passionate about applying 
technology and innovation to advance **sustainable development and high-impact engineering solutions**.
</div>

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/Bergonio2_ID.jfif


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/1ogaZOhiKkhOyLbhfWruCZaKuxNXRbceM/view?usp=drive_link # or /assets/resume/resume.pdf
intern-url: https://drive.google.com/file/d/1Erqxdf_imgY90qniHdLb191Xr4rFVEei/view?usp=drive_link
thesis-url: https://drive.google.com/file/d/1yYn3MEmm96nyiXLIE3Y8uHpD0HKCiIk8/view?usp=drive_link
certi-url: https://drive.google.com/file/d/1jW3p1M3bZt4Iu4LDJ-Gxxb8yyMvYYRXT/view?usp=drive_link
# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: test    # www.linkedin.com/in/jose-luis-bergonio-12464a255 
  github: test    # www.github.com/bergoniojoseluis
  stackoverflow:      # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: 3D Modeling
    tools:
    - Onshape
    - Solidworks
    - Creo
    - Fusion 360 (Autodesk)
    - Blender (for complex shapes or animations)
    - Siemens NX
    - Inventor (Autodesk)
    - CATIA (Dassault Systèmes)
  - category: Prototyping
    tools:
    - SLA
    - CNC
    - FDM
    - SLS
    - DMLS
    - PolyJet Printing
    - Vacuum Casting
    - Laser Cutting
    - Water Jet Cutting
    - Arduino / Raspberry Pi
    - Breadboarding for circuit testing
  - category: Design Standards / Practices
    tools:
    - GD&T ASME Y14
    - ISO fits and tolerances
    - PLM (PTC Windchill / Arena)   
  - category: PCB Design
    tools:
    - Altium Designer
    - Altium
    - Eagle 
    - KiCad
  - category: Problem Solving / Risk Management
    tools:
    - Root Cause Analysis (e.g., 5 Whys, Fishbone Diagram)
    - DFMEA / PFMEA 
    - Six Sigma methodologies
    - Shain Red-X


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/

    activities:
    output: true
    permalink: /activities/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects
  - _activities


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
